### ISSUE TITLE
Too large hit areas

### ISSUE THREAD

**Issue by danielsaidi** [nnhubbard/ZSPinAnnotation#11]
Hi,

Thanks for a nice approach to multi-colored pins!

I have problems with the hit area being too large. Instead of the hit area just being the pins bounding box, it extends quite a bit to the sides, as well as as taking up as much space below the pin as the pin is tall.

I assume that this is so that the pin will touch down exactly on the annotation coordinate, but you could use an offset to achieve this precise placing as well.

Do you happen to have a solution for this? If not, I'll have a look at the code and see if I can come up with a solution.

**Comment by nnhubbard** [comment]
No solution currently as I don't have enough time to look into it. You are welcome to submit a Pull Request if you have a chance to look into it!

**Comment by danielsaidi** [comment]
I like your approach with vector-based pins, but had a hard time modifying it. I decided to go with a totally different approach instead - https://github.com/danielsaidi/ColorPinAnnotationView
